### ISSUE TITLE
Importing glamorous doesn't work during jest tests (with create-react-app)

### ISSUE THREAD

**Issue by abkds** [nitin42/glamorous-primitives#6]
So I am using jest and enzyme in the project which was created using create-react-app. In testing a react component in which glamorous is being used to create views and text etc. Running even the simplest test of shallow rendering fails.

Here is the code :

```
import React from 'react';
import { shallow } from 'enzyme';

import GuaranteePage from '../Index';

it('shallow renders without crashing', () => {
  shallow(<GuaranteePage />);
});
```
GuaranteePage imports glamorous from 'glamorous-primitives'. When I run the test it says.
```

 FAIL  src/components/Guarantee/__tests__/Index.test.js
  ● Test suite failed to run

    /Users/abhishek/FlyHomes/final/client-web/node_modules/glamorous-primitives/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createGlamorous from './constructor/create-glamorous';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/components/Guarantee/Index.jsx:8:28)
      at Object.<anonymous> (src/components/Guarantee/__tests__/Index.test.js:3:14)
```
Any ideas on this ?

**Comment by nitin42** [comment]
Everything seems to be working on my side. These steps you can try to make it work - 

* Reinstall the package
* Create a basic component using `glamorous` and see whether it renders or not
* If it renders properly then may be you need to change your test configuration.
* Or if it doesn't render then reply with the stack trace

The problem is the stack trace you provided above is vague and I am not able to understand what is missing from my side.

Let me know1

**Comment by theinterned** [comment]
Hi, I'm seeing the same issue. 

Looks like this might be the problem: https://github.com/facebookincubator/create-react-app/issues/2879

**Comment by nitin42** [comment]
Thanks @theinterned! #7 fixes this.

**Comment by nitin42** [comment]
Oops, I forgot to include the new build files. I'll add them when I get home and will release the update patch. Thanks!

**Comment by theinterned** [comment]
Hi @nitin42 any chance you could deploy this fix to npm?

**Comment by nitin42** [comment]
Fixed!
