### ISSUE TITLE
"Unknown Prop Warning" when rendering glamorous-primitive with custom styles

### ISSUE THREAD

**Issue by theinterned** [nitin42/glamorous-primitives#8]
When I render conditional styles with props on my glamorous-primitives I get the following error when running Jest tests:

```sh
Warning: Unknown props `empty`,`done` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in div (at index.js:91)
        in Button
       ...
```

the component I'm rendering looks like this:

```js
const Button = glam.text(
  {
    textTransform: 'uppercase',
    textAlign: 'center',
    fontSize: 14,
  },
  ({ empty, done }) => ({
    color: (empty || done) ? emptyTextColor : textColor,
  })
);
```

The failing test is here https://github.com/theinterned/One-Big-Thing/blob/1-text-entry-component/src/App.test.js

**Comment by theinterned** [comment]
it looks like the `rootEl` being set here is type `Text` ... I'm unclear if this is appropriate for glamorous's whitelist?  https://glamorous.rocks/api#__next

**Comment by nitin42** [comment]
Ok! This might be a bug. Would you be interested if I add you as a collaborator on this project ? So you can make changes (or add features if you want). I am not able to manage my time to work on maintaining my open source projects. It may be while when I get back to do open source with more energy. Let me know!

**Comment by theinterned** [comment]
Hi sorry for the radio silence. I am working on this during company hack days ... so it's one day every 6 weeks (or more!) 

I'm happy to submit a PR for this issue.

**Comment by theinterned** [comment]
Please see notes in MR #14

**Comment by theinterned** [comment]
Closing this stale issue
